### ISSUE TITLE
Debug `task:ansible deps`

### ISSUE THREAD

**Issue by alex-matthews** [alex-matthews/test-cluster#238]
With the latest version of the template I am getting the following error (this is a clean fork):

```$ flux-cluster-template git:(main) task ansible:deps
$ task: [ansible:.venv] true &&  -m venv /Users/alex/flux-cluster-template/.venv
$ "-m": executable file not found in $PATH
$ task: Failed to run task "ansible:deps": exit status 127
```

**Comment by alex-matthews** [comment]
Issue possibly relates to https://github.com/onedr0p/flux-cluster-template/issues/1106, although I'm not using a devcontainer...

**Comment by philgood** [comment]
I had the same issue, resolved it by updating the file path in AnsibleTasks.yaml from:
`true && {{.PYTHON_BIN}}  -m venv {{.ROOT_DIR}}/.venv` to
`true && /opt/homebrew/bin/python3 -m venv {{.ROOT_DIR}}/.venv`

**Comment by alex-matthews** [comment]
Perfect, thanks! 🙌
